# Generated by Django 2.2.17 on 2021-05-02 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_auto_20210502_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branc', models.CharField(blank=True, choices=[('cse', 'cse'), ('is', 'is'), ('civil', 'civil'), ('mechanical', 'mechanical')], max_length=200, null=True)),
                ('sem', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True)),
                ('sec', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=200, null=True)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.Teacher')),
            ],
        ),
    ]
