# Generated by Django 2.2.17 on 2021-05-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0004_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='clas',
            new_name='teacher',
        ),
    ]
