# Generated by Django 2.2.17 on 2021-05-02 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0006_auto_20210502_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='branc',
            new_name='branch',
        ),
    ]
