# Generated by Django 2.2.17 on 2021-05-02 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0008_auto_20210502_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(blank=True, null=True)),
                ('clss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.Student')),
            ],
        ),
    ]
