# Generated by Django 2.2.17 on 2021-05-04 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0011_auto_20210504_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendence.Student'),
        ),
    ]
