# Generated by Django 2.2.17 on 2021-05-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0014_auto_20210507_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='branch',
            field=models.CharField(choices=[('cse', 'cse'), ('is', 'is'), ('civil', 'civil'), ('mechanical', 'mechanical')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='sec',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=200, null=True),
        ),
    ]
