# Generated by Django 2.2.17 on 2021-05-08 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0015_auto_20210508_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_present',
        ),
        migrations.AlterField(
            model_name='class',
            name='sem',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True),
        ),
        migrations.AlterField(
            model_name='count',
            name='clss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendence.Class'),
        ),
        migrations.AlterField(
            model_name='count',
            name='cnt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='count',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendence.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('cse', 'cse'), ('is', 'is'), ('civil', 'civil'), ('mechanical', 'mechanical')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sec',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
