# Generated by Django 2.2.17 on 2021-05-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0018_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('ISE', 'ISE'), ('Civil', 'Civil'), ('ME', 'ME'), ('Aeronautical', 'Aeronautical'), ('ECE', 'ECE'), ('Aerospace', 'Aerospace')], max_length=200, null=True),
        ),
    ]
