# Generated by Django 2.2.17 on 2021-05-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0020_auto_20210519_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='usn',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
