# Generated by Django 2.2.17 on 2021-05-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0021_auto_20210520_0610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='branch',
            new_name='department',
        ),
    ]
