# Generated by Django 2.2.17 on 2021-06-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0022_auto_20210520_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('sem', models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], max_length=200, null=True)),
                ('branch', models.CharField(blank=True, choices=[('CSE', 'CSE'), ('ISE', 'ISE'), ('Civil', 'Civil'), ('ME', 'ME'), ('Aeronautical', 'Aeronautical'), ('ECE', 'ECE'), ('Aerospace', 'Aerospace')], max_length=200, null=True)),
                ('ques', models.CharField(blank=True, max_length=200, null=True)),
                ('ans', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
