# Generated by Django 2.2.17 on 2021-06-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0024_auto_20210602_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='sem',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True),
        ),
    ]
