# Generated by Django 2.2.17 on 2021-06-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0025_auto_20210602_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(blank=True, max_length=200, null=True)),
                ('sem', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True)),
                ('branch', models.CharField(blank=True, choices=[('CSE', 'CSE'), ('ISE', 'ISE'), ('Civil', 'Civil'), ('ME', 'ME'), ('Aeronautical', 'Aeronautical'), ('ECE', 'ECE'), ('Aerospace', 'Aerospace')], max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tutorial',
            name='sub',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
