# Generated by Django 2.2.17 on 2021-06-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0027_auto_20210602_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('ISE', 'ISE'), ('Civil', 'Civil'), ('ME', 'ME'), ('Aeronautical', 'Aeronautical'), ('ECE', 'ECE'), ('Aerospace', 'Aerospace')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='sem',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)], null=True),
        ),
    ]
