# Generated by Django 2.2.17 on 2021-06-02 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0028_auto_20210602_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='sem',
        ),
    ]
