# Generated by Django 2.2.17 on 2021-06-03 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0029_auto_20210602_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('ques', models.CharField(blank=True, max_length=200, null=True)),
                ('ans', models.CharField(blank=True, max_length=200, null=True)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.Subject')),
            ],
        ),
    ]
