# Generated by Django 2.2.17 on 2021-06-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0031_importantquestions_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(blank=True, max_length=200, null=True)),
                ('ans', models.CharField(blank=True, max_length=200, null=True)),
                ('sub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendence.Subject')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.Type')),
            ],
        ),
    ]
