# Generated by Django 2.2.17 on 2021-06-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0032_item_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='tyPe',
        ),
    ]
