# Generated by Django 2.2.17 on 2021-06-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0034_item_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='ans',
            new_name='ans_description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='ques',
            new_name='ques_description',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='ans',
            new_name='ans_description',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='ques',
            new_name='ques_description',
        ),
        migrations.RenameField(
            model_name='questionpaper',
            old_name='ans',
            new_name='ans_description',
        ),
        migrations.RenameField(
            model_name='questionpaper',
            old_name='ques',
            new_name='ques_description',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='ans',
            new_name='ans_description',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='ques',
            new_name='ques_description',
        ),
        migrations.AddField(
            model_name='item',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='tutorials/'),
        ),
        migrations.AddField(
            model_name='note',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='tutorials/'),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='tutorials/'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='tutorials/'),
        ),
    ]
