# Generated by Django 2.2.17 on 2021-06-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0035_auto_20210603_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='document',
            new_name='document_ans',
        ),
        migrations.AddField(
            model_name='item',
            name='document_ques',
            field=models.FileField(blank=True, null=True, upload_to='tutorials/'),
        ),
    ]
