# Generated by Django 2.2.17 on 2021-06-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0036_auto_20210603_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='sub',
        ),
        migrations.AddField(
            model_name='type',
            name='image_url',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.DeleteModel(
            name='ImportantQuestions',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='QuestionPaper',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
    ]
