# Generated by Django 2.2.17 on 2021-07-17 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendence', '0037_auto_20210605_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exmtype', models.CharField(blank=True, choices=[('IA-1', 'IA-1'), ('IA-2', 'IA-2'), ('IA-3', 'IA-3')], max_length=200, null=True)),
                ('marks', models.IntegerField(null=True)),
                ('clss', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendence.Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
