# Generated by Django 2.2.17 on 2021-07-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0039_auto_20210717_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmark',
            old_name='marks',
            new_name='marks1',
        ),
        migrations.AddField(
            model_name='studentmark',
            name='marks2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='marks3',
            field=models.IntegerField(null=True),
        ),
    ]
